### ISSUE TITLE
scp export

### ISSUE THREAD

**Issue by alexskrc** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#2]
Hi there, I am trying to run the SCP export to an nfs share (hosted actually on the same CentOS7 vm where I am running Ansible from) and it always comes up with an "Exception 'content-type'". I used the examples here to build the playbook, the only difference is the share name: "server.ip://nfs/share/path", which is what works in the eport lc logs task (as opposed to "server.ip:/nfs/share/path"), but it doesn't seem to even hit the nfs server. Any ideas?
thanks in advance!
Alex

**Comment by rajeevarakkal** [comment]
Dear Alex,

We are looking into this issue your are facing. It will be great if you can clarify below points

1. I believe your facing issue with [dellemc_export_server_config_profile](https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC/blob/master/library/dellemc_export_server_config_profile.py) module.
2. The NFS share details you have provided is in the format of "server.ip://nfs/share/path"

Since the NFS share is in same server, why can't you give try to export the SCP into a local folder of Ansible system, [example ](https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC/blob/master/examples/export_server_config_profile_to_local_file.yml)?

With Regards
Rajeev

**Comment by alexskrc** [comment]
ok, more info: I set the ANSIBLE_KEEP_REMOTE_FILES=1 and picked up the script to run manually; it actually gets a reply:
omsdk.http.sdkhttpep:175 - Received SOAP reply:
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns.........

but then it comes up with:

ERROR - ansible.module_utils.dellemc_idrac:190 -  : EXCEPTION: Exporting Server Configuration Profile Method: 'NoneType' object has no attribute 'format'

this is with the local file.
Alex

**Comment by alexskrc** [comment]
I think I found the issue, I was at iDRAC 2.4, installed 2.52.52.52 and it exports fine now to the nfs share, when I try to export to the local path I get an error "Error: 'NoneType' object has no attribute 'format'", but I'm ok with nfs. Thanks for the quick reply!
Alex

**Comment by rajeevarakkal** [comment]
Thank you Alex & Good to know the issue is resolved. 

Unfortunately I couldn't respond  to your updates in time as it is midnight for me.  

Let us in case any further support required.

With Regards
Rajeev
